{% set name = "robotframework-sshlibrary" %}
{% set version = "3.3.0" %}
{% set sha256 = "fc5b5db63cf63a937bd4ada1a8b7508ec8a75d9454fa75e6410cbe72fd718de9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
  run:
    - paramiko >=1.15.3
    - python
    - robotframework >=3.0
    - scp >=0.13.0

test:
  imports:
    - SSHLibrary

about:
  home: https://github.com/robotframework/SSHLibrary
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Robot Framework test library for SSH and SFTP
  description: |
    SSHLibrary is operating system independent and supports Python 2.7 as well
    as Python 3.4 or newer. In addition to the normal Python interpreter, it
    also works with Jython 2.7.

    The library has the following main usages:

    - Executing commands on the remote machine, either with blocking or
      non-blocking behavior.
    - Writing and reading in an interactive shell.
    - Transferring files and directories over SFTP.
    - Ensuring that files and directories exist on the remote machine.
  doc_url: http://robotframework.org/SSHLibrary/SSHLibrary.html
  dev_url: https://github.com/robotframework/SSHLibrary

extra:
  recipe-maintainers:
    - bollwyvl
