travis:
  secure:
    BINSTAR_TOKEN: FAjhRoDziowNXOFKbLE9+ED2qEmT+7NkrNdiLshvbnvAsOkAY4gu2QrvqXGUEaai7SZnnB9if5XfIjwtlCITxVEPozqhmoOeNVv3/1RMKEZuZ7OrgonecUzBOkAjp5yplf0rp4E6wtIoZBuoXQ5+4SJ8gl6dlXlazrxR5hKdSyOmoWw6aec0IQESUQ3ugUkRV+PKRz9dkI29L/nnePvi8vUrDYhNkfxE3j5VcmmVd/Pf5lCHO8QnfBskJ+73mLaPEz6d1lCn6va1usID6SQtozwuemtk4Jb1MbM/o8+eJqRG6yL3+TyWKdRIXnUFl7EOaIK6t5wY32tsqMzi6TvONW6xbTEGSULEfBQpfZXO0d3NiDbxxJhkeWb3x2/jxtvpdT60pHRkfYGUvA1fQeRYNXeNeohDkUd+DZ/ky4c1H32IhvxJSDzZG2wXIR5GhgsIW7VeT/5o3upzMIiTPcN4R2+Hb62f6RMe8RPE4KRtBzGQdV3cUKN0pe5ck6gpK080dtDfLwuclihGweANxrItMoME1yKtones2obkreHoYUtsWADuSuZ/bcfjyHaIKaDaQY1sNi6TJjFvvDFRB28l+DfdaGh3XO8Y8haboxzycFsSfoPQP0+bs27UPUpNe5FdGHwywkR2v3EG//h8lBa+SLXyNyuFRiyR8l+AosHr9z8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
