travis:
  secure:
    BINSTAR_TOKEN: RPgKyFmx6rkulYyIXOX/+xxkHoNGNrdyLVUrsSy7EIM+Ng/4EXdy78jvQtFZN1+v+1+4poyYgXtbMZiJFsQeqYIAe711fv0Iwe0v0D2sMQZwAEwp0PLq1TPFSPJ9are/5KKo3YHWD/EgCI79ILqYrzxGCXdmPiXGSYokFSavo/+guvkQZeoFLNcj7lCturlDKqQ0h8pK/BML3h8ENeVsxEiYgYT1CfOMaSY1a3jcWN+lhvtnraWhzhVJenpA6qR/wj+KeA8NPOAZMR/fpAbbk2vf5gpfBDla+LDspbDRPAb1WZeMY5IDTlaUsPmOxpVCEyTReYuBrH8lz6kovokrFxrZFe/eiNFvUwgshaByp5hBPVvyFt/RdSFGvyhdt5x15v/4BqyXWgsBuRaZ7qioOZcGdZXYGAI03Eys/Z2Euq7Pwn8l4POVM5MhdiTnbylPNbWAwoatQcCJDjJvbRndV21Zv8RWPSp/xPe7Uz3UPswhsfXKIyaOGpqVmbCS/9VHf8HLUjTnQLhco/QAdaE1Bey0xmqhCUpkq/6CbNJxCYzLsCdNd1mQKGRIS0/8bScRyyE+vj9yYti52/+Ce9o7bvJH2VPhpPR5UEZ5NdVwTliBaHAo4ddi4DY57ogOyp8/KgzMztI1zBXc1M8RzuBAm4E1Qxl8WrerGuHrPO8A0js=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
